version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_datalake_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
